
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwgzpvnqtrtfgqqkhvnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3Z3pwdm5xdHJ0ZmdxcWtodm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzQ0NTUsImV4cCI6MjA1OTU1MDQ1NX0.ak5JSRGq4ldqF5at4wULebrgBoL_nLik190o1e-GcmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
